last_hashes:
  beat_demographics: ea74821f67e6dca94dbd35d76fa00b69
  pd_beats: b0fdd18e8abb1b58b7064acf1f8e1569
  pd_divisions: 4e6e6dbf43f188bca86ead441cc7fb62
  pd_neighborhoods: 4e6e6dbf43f188bca86ead441cc7fb62
last_package: metapack+file:///Users/eric/proj/data-projects/metatab-packages/crime-sandiego-collection/sandiego.gov-police_regions/_packages/sandiego.gov-police_regions-2.1.1/metadata.csv
