last_hashes:
  beat_demographics: b07fab4061a2a66be48aa0a990d0889e
  pd_beats: 22b61a8510a1c0d0940b0f7d20e73fe4
  pd_divisions: cc5537e1439fd59d6ff934f9fa7ada7f
  pd_neighborhoods: cc5537e1439fd59d6ff934f9fa7ada7f
last_package: metapack+file:///Users/eric/proj/data-projects/metatab-packages/sandiego/sandiego.gov/sandiego.gov-police_regions/_packages/sandiego.gov-police_regions-1.1.2/metadata.csv
